name: jekyll_commit

on:
  push:
    branches:
    - source

jobs:
  MyJob:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: source
    - name: Build
      run: |
        make all
    - name: Deploy
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        set -xo pipefail
        git checkout master
        ls -Q | grep -v _site | xargs rm -rf
        mv _site/* .
        rm -rf _site
        rm -rf .jekyll-cache
        [[ -n "$(git status --porcelain)" ]] || exit 0
        git add .
        git commit -m "Build $(git rev-parse source | grep -o '^.\{10\}')"
        git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master